### ISSUE TITLE
Configurable sort order

### ISSUE THREAD

**Issue by konaboy32** [Jaxc/Patreon-scripts#1]
First, great tool, thank you so much!
The Patreon export CSV is ordered by pledge descending.  So the Patron with highest pledge is at the top of the output file.
It would be nice to sort on other columns, such as Start ascending, or Lifetime descending.
Perhaps add sort column and order as parameters, or to a config file.
cheers!

**Comment by Jaxc** [comment]
Different sorting options added in patch : 54f1e178065344815a5a276ce7bc0ac3e9805c06
